# -*-coding:UTF-8-*-
# import sqlite3
# conn = sqlite3.connect('stu.db')
# cursor=conn.cursor()
# cursor.execute('create table user (UserNumber varchar(12) primary key,UserName varchar(255),UserAge integer(2))')
# cursor.execute('create table if not exists user (UserNumber varchar(12) primary key,UserName varchar(255),UserAge integer(2))')
import sqlite3
conn = sqlite3.connect('../stu.db')
c=conn.cursor()
c.execute('create table addresslist (stuno varchar(10) primary key,stuname varchar(20),telnum varchar(15),address varchar(30))');
c.execute("insert into addresslist (stuno,stuname,telnum,address) values('001','张三','123','济南')")
c.execute("insert into addresslist (stuno,stuname,telnum,address) values('002','李四','124','泰安')")
c.execute("insert into addresslist (stuno,stuname,telnum,address) values('003','王五','125','济宁')")
c.execute("insert into addresslist (stuno,stuname,telnum,address) values('004','李六','126','青岛')")
c.execute("insert into addresslist (stuno,stuname,telnum,address) values('005','孙七','127','潍坊')")
c.execute("insert into addresslist (stuno,stuname,telnum,address) values('006','赵八','128','北京')")
c.execute("insert into addresslist (stuno,stuname,telnum,address) values('007','钱九','129','上海')")
c.execute("insert into addresslist (stuno,stuname,telnum,address) values('008','周十','130','新疆')")
c.execute("insert into addresslist (stuno,stuname,telnum,address) values('009','吴十一','131','蒙古')")
c.execute("insert into addresslist (stuno,stuname,telnum,address) values('010','郑十二','132','黑龙江')")
c.execute('select * from addresslist')
Values = c.fetchall()
print(Values)
c.close()
conn.commit()